'use client'

import Banner from "@/components/banner/banner";
import { Container, FormControl, Menu, MenuItem, Select, SelectChangeEvent, Stack, Typography } from "@mui/material";
import type { Metadata } from "next";
import { useState } from "react";


// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function OlympicLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {

	const [state, setState] = useState({ sport: 'archery' })

	const handleChange = (event: SelectChangeEvent<string>) => {
		const name = event.target.name;
		const value = event.target.value;

		setState(prev => ({ ...prev, [name]: value }));
	};

	return (
		<>
			<Banner image="/test.jpg" text={state.sport} />
			<Container>
				<Stack direction='row' alignItems={'center'} spacing={3} mb={3}>
					<Typography variant='h4'>Sports </Typography>
					<FormControl
						variant="outlined"
						sx={{
							minWidth: 130,
							m: "0rem 1rem 0rem 1rem",
							height: "2.7rem",
						}}
					>
						<Select
							sx={{ height: "100%", textAlign: "left" }}
							value={state.sport}
							className="input-label-select"
							onChange={handleChange}
							displayEmpty
							name="sport"
						>
							<MenuItem className="input-label-option" value="archery">
								Archery
							</MenuItem>

							<MenuItem value={'athletics'}>
								Athletics
							</MenuItem>

							<MenuItem value={'badminton'}>
								Badminton
							</MenuItem>
							<MenuItem value={'boxing'}>
								Boxing
							</MenuItem>
							<MenuItem value={'shooting'}>
								Shooting
							</MenuItem>

						</Select>
					</FormControl>
				</Stack>
				{children}
			</Container>
		</>
	);
}
